//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Drawer3D.Model.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FigureValidator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FigureValidator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Drawer3D.Model.Resources.FigureValidator", typeof(FigureValidator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо создать проект..
        /// </summary>
        public static string AppNotConnected {
            get {
                return ResourceManager.GetString("AppNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Высота стен вектора {0} может быть от {1} до {2}..
        /// </summary>
        public static string HeightWalls {
            get {
                return ResourceManager.GetString("HeightWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество стен вдоль вектора {0} равно {1}..
        /// </summary>
        public static string MaxCountWalls {
            get {
                return ResourceManager.GetString("MaxCountWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Точка {0} вектора {1} не принадлежит допустимой границе от {2} до {3}..
        /// </summary>
        public static string PointBorder {
            get {
                return ResourceManager.GetString("PointBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Между точками {0} и {1} вектора {2} требуется минимальный интервал {3}..
        /// </summary>
        public static string PointsInterval {
            get {
                return ResourceManager.GetString("PointsInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер вектора {0} может быть от {1} до {2}..
        /// </summary>
        public static string SizeVector {
            get {
                return ResourceManager.GetString("SizeVector", resourceCulture);
            }
        }
    }
}
